### ISSUE TITLE
 general questions

### ISSUE THREAD

**Issue by maabed** [subvisual/tripl.it#23]
Some general questions:
- Is this repo is the same that contain the application in the app store?
- What is the cordova plugin or package that you use to access phone contacts?

Thanks for great app

**Comment by gabrielpoca** [comment]
Hi @maabed, this is not the same application that's on the app store, it is going to be :P this one is still work in progress, the one in the app store is using [this](https://github.com/apache/cordova-plugin-contacts) plugin

**Comment by maabed** [comment]
Thanks @gabrielpoca for replay,
What is the best approach to invoke the contacts plugin functionality, i'm using deps.autorun to insure i have the latest contacts updates but there is a slow in contacts loading, its better to invoke it onBeforeAction? or if you have a better solution.

**Comment by gabrielpoca** [comment]
@maabed the application on the app store is made with backbone. I had the same problem, the plugin is really slow (see [here](https://issues.apache.org/jira/browse/CB-2637?jql=project%20%3D%20CB%20AND%20component%20%3D%20%22Plugin%20Contacts%22%20AND%20text%20~%20%22slow%22)). In my case, I removed the the feature of listing all users, I only allow for searching with a filter of three characters. I have some ideas on requesting the contacts beforehand and storing them on localstorage/websql/something, but then I wouldn't know when to update them. I guess this would require a custom phonegap plugin where you could register a callback when the contacts change. Maybe someone has already released a solution for this, I don't know. I'm sorry I can't help you more.
